### ISSUE TITLE
[Issue]: RBA Data Source Review Dashboard issues

### ISSUE THREAD

**Issue by ccl0utier** [splunk/rba#102]
### Description

The dashboard seems to have a few issues, for example:

- Panels are not restricted to Risk Rules, for example, It shows an incorrect count of detections populating the Risk index (which should have the `Risk Analysis` action enabled), etc.  Maybe add `AND match('actions',"risk")` to the filter of the base search?
- MITRE extractions (from search?) seem to be broken.  Might want to get those from annotations?
- The dashboard might benefit from simplifying the base search to:
```
| rest splunk_server=local count=0 /servicesNS/-/SplunkEnterpriseSecuritySuite/saved/searches 
| where match('action.correlationsearch.enabled', "1|[Tt]|[Tt][Rr][Uu][Ee]") 
| where disabled=0
```
... and putting additional logic in the relevant panel search.  Otherwise the base search extracts fields that might never be used.
- The `| rest` call above could be further optimized by explicitly requesting only the necessary fields, i.e.: `| rest splunk_server=local count=0 /servicesNS/-/SplunkEnterpriseSecuritySuite/saved/searches f=field1 f=field2 f=field3`

I'm happy to help fix those if that makes sense.

### Related links

- [Issue](https://splunk.github.io/rba/)

**Comment by ZachTheSplunker** [comment]
Thanks for pointing this out! And yes, if you would like to open up a pull request with changes, that would be much appreciated!
